//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public string ISBN { get; set; }
        public string Author { get; set; }
        public int PublisherID { get; set; }
        public int Year { get; set; }
    
        public virtual Publishers Publishers { get; set; }
    }
}
